#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/baiduzhidao/baiduzhidao/spiders
ps -ef | grep scrapy | grep zhidao | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl zhidao >$OPENSHIFT_DATA_DIR/zhidao_log.txt 2>&1 &
