#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
#rm -rf $OPENSHIFT_DATA_DIR/zhidao/*
spider_name="zhidao"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/baiduzhidao/baiduzhidao/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

spider_name="lefeng_product"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/$spider_name/$spider_name/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

spider_name="jumeiProduct"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/$spider_name/$spider_name/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

spider_name="kimissValue"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/$spider_name/$spider_name/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

spider_name="tmall"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/$spider_name/$spider_name/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

spider_name="tmall_fp_product"
cd $OPENSHIFT_DEPLOYMENTS_DIR/201*/repo/spider/$spider_name/$spider_name/spiders
ps -ef | grep scrapy | grep $spider_name | awk '{print $2}' | xargs -n 1 -r kill -9
scrapy crawl $spider_name >"$OPENSHIFT_DATA_DIR/$spider_name""_log.txt" 2>&1 &

