curl -v spider1-dbn.rhcloud.com &
curl -v spider2-dbn.rhcloud.com &
curl -v spider3-dbn.rhcloud.com &
curl -v spider1-dbn1.rhcloud.com &
curl -v spider2-dbn1.rhcloud.com &
curl -v spider3-dbn1.rhcloud.com &
curl -v spider1-dbn2.rhcloud.com &
curl -v spider2-dbn2.rhcloud.com &
curl -v spider3-dbn2.rhcloud.com &
curl -v spider1-dbn3.rhcloud.com &
curl -v spider2-dbn3.rhcloud.com &
curl -v spider3-dbn3.rhcloud.com &
curl -v spider1-dbn4.rhcloud.com &
curl -v spider2-dbn4.rhcloud.com &
curl -v spider3-dbn4.rhcloud.com &
curl -v spider1-dbn5.rhcloud.com &
curl -v spider2-dbn5.rhcloud.com &
curl -v spider3-dbn5.rhcloud.com &
curl -v spider1-dbn6.rhcloud.com &
curl -v spider2-dbn6.rhcloud.com &
curl -v spider3-dbn6.rhcloud.com &
curl -v spider1-dbn7.rhcloud.com &
curl -v spider2-dbn7.rhcloud.com &
curl -v spider3-dbn7.rhcloud.com &
